##########################################################
##################  所有profile共有的配置  #################
##########################################################
spring:
  profiles:
    active: dev

---
###################  项目启动端口  ###################
server:
  port: 8080

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  resources:
    static-locations: classpath:/static/,classpath:/webjars/**
  devtools:
    livereload:
      enabled: true


logging:
  level.root: info
  path: /Users/wanghongjie/springboot/anysign-cloud-service/anysign-cloud-parent/logs/
  file: anysign-seal-server.log
  config: classpath:logback-spring.xml


---
##########################################################
###################  正式环境的profile  ###################
##########################################################

spring:
  profiles: pro

logging:
  level.root: ERROR
  path: logs/
  file: anysign-seal-server.log