appId: APP_659E04EA1D284A1EB1E58DD393823FD1
deviceId: DEV_7FF40A32D91943DD961AF607A2A53F53
secret: 7gHJIqmzEeg2lYSCdtkvWFiQZPOBBfeM
version: 1.0

signature:
  address: http://192.168.20.6:8081/cloudsign/v1
  user-apply-cert: /userApplyCert
  deposit-cert-sign: /depositCertSign
  verify-sign: /verifySign
tss:
  address: http://192.168.20.6:8081/tss/v1/timestamp
  gen-ts-req: /genTsReq
  gen-ts-resp: /genTsResp
dsvs:
  address: http://192.168.20.6:8081/dsvs/v1
  cert-validate: /cert/validate
file:
  address: http://192.168.37.100:10019
  upload: /upload
  download: /download
