##########################################################
##################  所有profile共有的配置  #################
##########################################################

spring:
  profiles:
    active: @env@
  application:
    name: anysign-template-server
###################  项目启动端口  ###################
server:
  port: 10503
  tomcat:
    basedir: ./tmp
    background-processor-delay: 30
    max-http-post-size: 10000000
    accesslog:
      enabled: true
      buffered: true
      directory: ./log
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
      prefix: access_log
      suffix: .log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true

logging:
  level.root: info
  path: logs/
  file: anysign-template-server.log
  config: classpath:logback-spring.xml
